// Decompiled with JetBrains decompiler
// Type: ReClassNET.Forms.SettingsForm
// Assembly: ReClass.NET, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 92B1334E-F9AF-41DF-AFE3-F9686CA00880
// Assembly location: C:\Users\Mariu\Documents\ReClass\PS4\ReClass.NET.exe

using ReClassNET.Controls;
using ReClassNET.Extensions;
using ReClassNET.Native;
using ReClassNET.Project;
using ReClassNET.Properties;
using ReClassNET.UI;
using ReClassNET.Util;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace ReClassNET.Forms
{
  public class SettingsForm : IconForm
  {
    private readonly ReClassNET.Settings settings;
    private readonly CppTypeMapping typeMapping;
    private IContainer components;
    private TabControl settingsTabControl;
    private TabPage generalSettingsTabPage;
    private TabPage colorsSettingTabPage;
    private TabPage typeDefinitionsSettingsTabPage;
    private CheckBox stayOnTopCheckBox;
    private GroupBox displayGroupBox;
    private CheckBox showNodeAddressCheckBox;
    private CheckBox showTextCheckBox;
    private CheckBox showNodeOffsetCheckBox;
    private CheckBox highlightChangedValuesCheckBox;
    private GroupBox commentsGroupBox;
    private CheckBox showRttiCheckBox;
    private CheckBox showPointerCheckBox;
    private CheckBox showIntegerCheckBox;
    private CheckBox showFloatCheckBox;
    private CheckBox showPluginInfoCheckBox;
    private CheckBox showStringCheckBox;
    private CheckBox showSymbolsCheckBox;
    private ColorBox backgroundColorBox;
    private Label nodeSelectedLabel;
    private ColorBox nodeSelectedColorBox;
    private Label nodeHiddenLabel;
    private ColorBox nodeHiddenColorBox;
    private Label nodeAddressLabel;
    private ColorBox nodeAddressColorBox;
    private Label nodeOffsetLabel;
    private ColorBox nodeOffsetColorBox;
    private Label nodeHexValueLabel;
    private ColorBox nodeHexValueColorBox;
    private Label backgroundLabel;
    private Label nodeValueLabel;
    private ColorBox nodeValueColorBox;
    private Label nodeNameLabel;
    private ColorBox nodeNameColorBox;
    private Label nodeTypeLabel;
    private ColorBox nodeTypeColorBox;
    private Label nodeVTableLabel;
    private ColorBox nodeVTableColorBox;
    private Label nodeTextLabel;
    private ColorBox nodeTextColorBox;
    private Label nodeCommentLabel;
    private ColorBox nodeCommentColorBox;
    private Label nodeIndexLabel;
    private ColorBox nodeIndexColorBox;
    private Label nodePluginLabel;
    private ColorBox nodePluginColorBox;
    private Label floatSettingsLabel;
    private TextBox floatTypeTextBox;
    private Label uint64SettingsLabel;
    private TextBox uint64TypeTextBox;
    private Label uint32SettingsLabel;
    private TextBox uint32TypeTextBox;
    private Label uint16SettingsLabel;
    private TextBox uint16TypeTextBox;
    private Label uint8SettingsLabel;
    private TextBox uint8TypeTextBox;
    private Label int64SettingsLabel;
    private TextBox int64TypeTextBox;
    private Label int32SettingsLabel;
    private TextBox int32TypeTextBox;
    private Label int16SettingsLabel;
    private TextBox int16TypeTextBox;
    private Label int8SettingsLabel;
    private TextBox int8TypeTextBox;
    private Label functionPtrSettingsLabel;
    private TextBox functionPtrTypeTextBox;
    private Label utf16TextSettingsLabel;
    private TextBox utf16TextTypeTextBox;
    private Label utf8TextSettingsLabel;
    private TextBox utf8TextTypeTextBox;
    private Label matrix3x3SettingsLabel;
    private TextBox matrix3x3TypeTextBox;
    private Label matrix3x4SettingsLabel;
    private TextBox matrix3x4TypeTextBox;
    private Label matrix4x4SettingsLabel;
    private TextBox matrix4x4TypeTextBox;
    private Label vector2SettingsLabel;
    private TextBox vector2TypeTextBox;
    private Label vector3SettingsLabel;
    private TextBox vector3TypeTextBox;
    private Label vector4SettingsLabel;
    private TextBox vector4TypeTextBox;
    private Label doubleSettingsLabel;
    private TextBox doubleTypeTextBox;
    private GroupBox nodeColorGroupBox;
    private Label generatorInfoLabel;
    private BannerBox bannerBox;
    private Label boolSettingsLabel;
    private TextBox boolTypeTextBox;
    private GroupBox fileAssociationGroupBox;
    private Button removeAssociationButton;
    private Button createAssociationButton;
    private Label associationInfoLabel;
    private CheckBox randomizeWindowTitleCheckBox;
    private CheckBox runAsAdminCheckBox;
    private Label nuintSettingsLabel;
    private TextBox nuintTypeTextBox;
    private Label nintSettingsLabel;
    private TextBox nintTypeTextBox;
    private Label utf32TextSettingsLabel;
    private TextBox utf32TextTypeTextBox;

    public TabControl SettingsTabControl
    {
      get
      {
        return this.settingsTabControl;
      }
    }

    public SettingsForm(ReClassNET.Settings settings, CppTypeMapping typeMapping)
    {
      this.settings = settings;
      this.typeMapping = typeMapping;
      this.InitializeComponent();
      this.settingsTabControl.ImageList = new ImageList()
      {
        Images = {
          (Image) Resources.B16x16_Gear,
          (Image) Resources.B16x16_Color_Wheel,
          (Image) Resources.B16x16_Settings_Edit
        }
      };
      this.generalSettingsTabPage.ImageIndex = 0;
      this.colorsSettingTabPage.ImageIndex = 1;
      this.typeDefinitionsSettingsTabPage.ImageIndex = 2;
      this.SetGeneralBindings();
      this.SetColorBindings();
      this.SetTypeDefinitionBindings();
      if (NativeMethods.IsUnix())
      {
        this.fileAssociationGroupBox.Enabled = false;
        this.runAsAdminCheckBox.Enabled = false;
      }
      else
      {
        NativeMethodsWindows.SetButtonShield(this.createAssociationButton, true);
        NativeMethodsWindows.SetButtonShield(this.removeAssociationButton, true);
      }
    }

    protected override void OnLoad(EventArgs e)
    {
      base.OnLoad(e);
      GlobalWindowManager.AddWindow((Form) this);
    }

    protected override void OnFormClosed(FormClosedEventArgs e)
    {
      base.OnFormClosed(e);
      GlobalWindowManager.RemoveWindow((Form) this);
    }

    private void createAssociationButton_Click(object sender, EventArgs e)
    {
      WinUtil.RunElevated(PathUtil.LauncherExecutablePath, "-registerfileext");
    }

    private void removeAssociationButton_Click(object sender, EventArgs e)
    {
      WinUtil.RunElevated(PathUtil.LauncherExecutablePath, "-unregisterfileext");
    }

    private static void SetBinding(
      IBindableComponent control,
      string propertyName,
      object dataSource,
      string dataMember)
    {
      control.DataBindings.Add(propertyName, dataSource, dataMember, true, DataSourceUpdateMode.OnPropertyChanged);
    }

    private void SetGeneralBindings()
    {
      SettingsForm.SetBinding((IBindableComponent) this.stayOnTopCheckBox, "Checked", (object) this.settings, "StayOnTop");
      this.stayOnTopCheckBox.CheckedChanged += (EventHandler) ((_, _2) => GlobalWindowManager.Windows.ForEach<Form>((Action<Form>) (w => w.TopMost = this.stayOnTopCheckBox.Checked)));
      SettingsForm.SetBinding((IBindableComponent) this.showNodeAddressCheckBox, "Checked", (object) this.settings, "ShowNodeAddress");
      SettingsForm.SetBinding((IBindableComponent) this.showNodeOffsetCheckBox, "Checked", (object) this.settings, "ShowNodeOffset");
      SettingsForm.SetBinding((IBindableComponent) this.showTextCheckBox, "Checked", (object) this.settings, "ShowNodeText");
      SettingsForm.SetBinding((IBindableComponent) this.highlightChangedValuesCheckBox, "Checked", (object) this.settings, "HighlightChangedValues");
      SettingsForm.SetBinding((IBindableComponent) this.showFloatCheckBox, "Checked", (object) this.settings, "ShowCommentFloat");
      SettingsForm.SetBinding((IBindableComponent) this.showIntegerCheckBox, "Checked", (object) this.settings, "ShowCommentInteger");
      SettingsForm.SetBinding((IBindableComponent) this.showPointerCheckBox, "Checked", (object) this.settings, "ShowCommentPointer");
      SettingsForm.SetBinding((IBindableComponent) this.showRttiCheckBox, "Checked", (object) this.settings, "ShowCommentRtti");
      SettingsForm.SetBinding((IBindableComponent) this.showSymbolsCheckBox, "Checked", (object) this.settings, "ShowCommentSymbol");
      SettingsForm.SetBinding((IBindableComponent) this.showStringCheckBox, "Checked", (object) this.settings, "ShowCommentString");
      SettingsForm.SetBinding((IBindableComponent) this.showPluginInfoCheckBox, "Checked", (object) this.settings, "ShowCommentPluginInfo");
      SettingsForm.SetBinding((IBindableComponent) this.runAsAdminCheckBox, "Checked", (object) this.settings, "RunAsAdmin");
      SettingsForm.SetBinding((IBindableComponent) this.randomizeWindowTitleCheckBox, "Checked", (object) this.settings, "RandomizeWindowTitle");
    }

    private void SetColorBindings()
    {
      SettingsForm.SetBinding((IBindableComponent) this.backgroundColorBox, "Color", (object) this.settings, "BackgroundColor");
      SettingsForm.SetBinding((IBindableComponent) this.nodeSelectedColorBox, "Color", (object) this.settings, "SelectedColor");
      SettingsForm.SetBinding((IBindableComponent) this.nodeHiddenColorBox, "Color", (object) this.settings, "HiddenColor");
      SettingsForm.SetBinding((IBindableComponent) this.nodeAddressColorBox, "Color", (object) this.settings, "AddressColor");
      SettingsForm.SetBinding((IBindableComponent) this.nodeOffsetColorBox, "Color", (object) this.settings, "OffsetColor");
      SettingsForm.SetBinding((IBindableComponent) this.nodeHexValueColorBox, "Color", (object) this.settings, "HexColor");
      SettingsForm.SetBinding((IBindableComponent) this.nodeTypeColorBox, "Color", (object) this.settings, "TypeColor");
      SettingsForm.SetBinding((IBindableComponent) this.nodeNameColorBox, "Color", (object) this.settings, "NameColor");
      SettingsForm.SetBinding((IBindableComponent) this.nodeValueColorBox, "Color", (object) this.settings, "ValueColor");
      SettingsForm.SetBinding((IBindableComponent) this.nodeIndexColorBox, "Color", (object) this.settings, "IndexColor");
      SettingsForm.SetBinding((IBindableComponent) this.nodeVTableColorBox, "Color", (object) this.settings, "VTableColor");
      SettingsForm.SetBinding((IBindableComponent) this.nodeCommentColorBox, "Color", (object) this.settings, "CommentColor");
      SettingsForm.SetBinding((IBindableComponent) this.nodeTextColorBox, "Color", (object) this.settings, "TextColor");
      SettingsForm.SetBinding((IBindableComponent) this.nodePluginColorBox, "Color", (object) this.settings, "PluginColor");
    }

    private void SetTypeDefinitionBindings()
    {
      SettingsForm.SetBinding((IBindableComponent) this.boolTypeTextBox, "Text", (object) this.typeMapping, "TypeBool");
      SettingsForm.SetBinding((IBindableComponent) this.int8TypeTextBox, "Text", (object) this.typeMapping, "TypeInt8");
      SettingsForm.SetBinding((IBindableComponent) this.int16TypeTextBox, "Text", (object) this.typeMapping, "TypeInt16");
      SettingsForm.SetBinding((IBindableComponent) this.int32TypeTextBox, "Text", (object) this.typeMapping, "TypeInt32");
      SettingsForm.SetBinding((IBindableComponent) this.int64TypeTextBox, "Text", (object) this.typeMapping, "TypeInt64");
      SettingsForm.SetBinding((IBindableComponent) this.nintTypeTextBox, "Text", (object) this.typeMapping, "TypeNInt");
      SettingsForm.SetBinding((IBindableComponent) this.uint8TypeTextBox, "Text", (object) this.typeMapping, "TypeUInt8");
      SettingsForm.SetBinding((IBindableComponent) this.uint16TypeTextBox, "Text", (object) this.typeMapping, "TypeUInt16");
      SettingsForm.SetBinding((IBindableComponent) this.uint32TypeTextBox, "Text", (object) this.typeMapping, "TypeUInt32");
      SettingsForm.SetBinding((IBindableComponent) this.uint64TypeTextBox, "Text", (object) this.typeMapping, "TypeUInt64");
      SettingsForm.SetBinding((IBindableComponent) this.nuintTypeTextBox, "Text", (object) this.typeMapping, "TypeNUInt");
      SettingsForm.SetBinding((IBindableComponent) this.floatTypeTextBox, "Text", (object) this.typeMapping, "TypeFloat");
      SettingsForm.SetBinding((IBindableComponent) this.doubleTypeTextBox, "Text", (object) this.typeMapping, "TypeDouble");
      SettingsForm.SetBinding((IBindableComponent) this.vector2TypeTextBox, "Text", (object) this.typeMapping, "TypeVector2");
      SettingsForm.SetBinding((IBindableComponent) this.vector3TypeTextBox, "Text", (object) this.typeMapping, "TypeVector3");
      SettingsForm.SetBinding((IBindableComponent) this.vector4TypeTextBox, "Text", (object) this.typeMapping, "TypeVector4");
      SettingsForm.SetBinding((IBindableComponent) this.matrix3x3TypeTextBox, "Text", (object) this.typeMapping, "TypeMatrix3x3");
      SettingsForm.SetBinding((IBindableComponent) this.matrix3x4TypeTextBox, "Text", (object) this.typeMapping, "TypeMatrix3x4");
      SettingsForm.SetBinding((IBindableComponent) this.matrix4x4TypeTextBox, "Text", (object) this.typeMapping, "TypeMatrix4x4");
      SettingsForm.SetBinding((IBindableComponent) this.utf8TextTypeTextBox, "Text", (object) this.typeMapping, "TypeUtf8Text");
      SettingsForm.SetBinding((IBindableComponent) this.utf16TextTypeTextBox, "Text", (object) this.typeMapping, "TypeUtf16Text");
      SettingsForm.SetBinding((IBindableComponent) this.utf32TextTypeTextBox, "Text", (object) this.typeMapping, "TypeUtf32Text");
      SettingsForm.SetBinding((IBindableComponent) this.functionPtrTypeTextBox, "Text", (object) this.typeMapping, "TypeFunctionPtr");
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.settingsTabControl = new TabControl();
      this.generalSettingsTabPage = new TabPage();
      this.fileAssociationGroupBox = new GroupBox();
      this.removeAssociationButton = new Button();
      this.createAssociationButton = new Button();
      this.associationInfoLabel = new Label();
      this.commentsGroupBox = new GroupBox();
      this.showPluginInfoCheckBox = new CheckBox();
      this.showStringCheckBox = new CheckBox();
      this.showSymbolsCheckBox = new CheckBox();
      this.showRttiCheckBox = new CheckBox();
      this.showPointerCheckBox = new CheckBox();
      this.showIntegerCheckBox = new CheckBox();
      this.showFloatCheckBox = new CheckBox();
      this.displayGroupBox = new GroupBox();
      this.randomizeWindowTitleCheckBox = new CheckBox();
      this.runAsAdminCheckBox = new CheckBox();
      this.highlightChangedValuesCheckBox = new CheckBox();
      this.showTextCheckBox = new CheckBox();
      this.showNodeOffsetCheckBox = new CheckBox();
      this.showNodeAddressCheckBox = new CheckBox();
      this.stayOnTopCheckBox = new CheckBox();
      this.colorsSettingTabPage = new TabPage();
      this.nodeColorGroupBox = new GroupBox();
      this.nodeValueLabel = new Label();
      this.nodePluginLabel = new Label();
      this.nodeHexValueColorBox = new ColorBox();
      this.nodePluginColorBox = new ColorBox();
      this.nodeHexValueLabel = new Label();
      this.nodeVTableLabel = new Label();
      this.nodeOffsetColorBox = new ColorBox();
      this.nodeVTableColorBox = new ColorBox();
      this.nodeOffsetLabel = new Label();
      this.nodeTextLabel = new Label();
      this.nodeAddressColorBox = new ColorBox();
      this.nodeTextColorBox = new ColorBox();
      this.nodeAddressLabel = new Label();
      this.nodeCommentLabel = new Label();
      this.nodeHiddenColorBox = new ColorBox();
      this.nodeCommentColorBox = new ColorBox();
      this.nodeHiddenLabel = new Label();
      this.nodeIndexLabel = new Label();
      this.nodeSelectedColorBox = new ColorBox();
      this.nodeIndexColorBox = new ColorBox();
      this.nodeSelectedLabel = new Label();
      this.nodeTypeColorBox = new ColorBox();
      this.nodeValueColorBox = new ColorBox();
      this.nodeTypeLabel = new Label();
      this.nodeNameLabel = new Label();
      this.nodeNameColorBox = new ColorBox();
      this.backgroundLabel = new Label();
      this.backgroundColorBox = new ColorBox();
      this.typeDefinitionsSettingsTabPage = new TabPage();
      this.nuintSettingsLabel = new Label();
      this.nuintTypeTextBox = new TextBox();
      this.nintSettingsLabel = new Label();
      this.nintTypeTextBox = new TextBox();
      this.boolSettingsLabel = new Label();
      this.boolTypeTextBox = new TextBox();
      this.generatorInfoLabel = new Label();
      this.functionPtrSettingsLabel = new Label();
      this.functionPtrTypeTextBox = new TextBox();
      this.utf16TextSettingsLabel = new Label();
      this.utf16TextTypeTextBox = new TextBox();
      this.utf8TextSettingsLabel = new Label();
      this.utf8TextTypeTextBox = new TextBox();
      this.matrix3x3SettingsLabel = new Label();
      this.matrix3x3TypeTextBox = new TextBox();
      this.matrix3x4SettingsLabel = new Label();
      this.matrix3x4TypeTextBox = new TextBox();
      this.matrix4x4SettingsLabel = new Label();
      this.matrix4x4TypeTextBox = new TextBox();
      this.vector2SettingsLabel = new Label();
      this.vector2TypeTextBox = new TextBox();
      this.vector3SettingsLabel = new Label();
      this.vector3TypeTextBox = new TextBox();
      this.vector4SettingsLabel = new Label();
      this.vector4TypeTextBox = new TextBox();
      this.doubleSettingsLabel = new Label();
      this.doubleTypeTextBox = new TextBox();
      this.floatSettingsLabel = new Label();
      this.floatTypeTextBox = new TextBox();
      this.uint64SettingsLabel = new Label();
      this.uint64TypeTextBox = new TextBox();
      this.uint32SettingsLabel = new Label();
      this.uint32TypeTextBox = new TextBox();
      this.uint16SettingsLabel = new Label();
      this.uint16TypeTextBox = new TextBox();
      this.uint8SettingsLabel = new Label();
      this.uint8TypeTextBox = new TextBox();
      this.int64SettingsLabel = new Label();
      this.int64TypeTextBox = new TextBox();
      this.int32SettingsLabel = new Label();
      this.int32TypeTextBox = new TextBox();
      this.int16SettingsLabel = new Label();
      this.int16TypeTextBox = new TextBox();
      this.int8SettingsLabel = new Label();
      this.int8TypeTextBox = new TextBox();
      this.bannerBox = new BannerBox();
      this.utf32TextSettingsLabel = new Label();
      this.utf32TextTypeTextBox = new TextBox();
      this.settingsTabControl.SuspendLayout();
      this.generalSettingsTabPage.SuspendLayout();
      this.fileAssociationGroupBox.SuspendLayout();
      this.commentsGroupBox.SuspendLayout();
      this.displayGroupBox.SuspendLayout();
      this.colorsSettingTabPage.SuspendLayout();
      this.nodeColorGroupBox.SuspendLayout();
      this.typeDefinitionsSettingsTabPage.SuspendLayout();
      this.bannerBox.BeginInit();
      this.SuspendLayout();
      this.settingsTabControl.Controls.Add((Control) this.generalSettingsTabPage);
      this.settingsTabControl.Controls.Add((Control) this.colorsSettingTabPage);
      this.settingsTabControl.Controls.Add((Control) this.typeDefinitionsSettingsTabPage);
      this.settingsTabControl.Location = new Point(12, 60);
      this.settingsTabControl.Name = "settingsTabControl";
      this.settingsTabControl.SelectedIndex = 0;
      this.settingsTabControl.Size = new Size(562, 355);
      this.settingsTabControl.TabIndex = 1;
      this.generalSettingsTabPage.Controls.Add((Control) this.fileAssociationGroupBox);
      this.generalSettingsTabPage.Controls.Add((Control) this.commentsGroupBox);
      this.generalSettingsTabPage.Controls.Add((Control) this.displayGroupBox);
      this.generalSettingsTabPage.Controls.Add((Control) this.stayOnTopCheckBox);
      this.generalSettingsTabPage.Location = new Point(4, 22);
      this.generalSettingsTabPage.Name = "generalSettingsTabPage";
      this.generalSettingsTabPage.Padding = new Padding(3);
      this.generalSettingsTabPage.Size = new Size(554, 329);
      this.generalSettingsTabPage.TabIndex = 0;
      this.generalSettingsTabPage.Text = "General";
      this.generalSettingsTabPage.UseVisualStyleBackColor = true;
      this.fileAssociationGroupBox.Controls.Add((Control) this.removeAssociationButton);
      this.fileAssociationGroupBox.Controls.Add((Control) this.createAssociationButton);
      this.fileAssociationGroupBox.Controls.Add((Control) this.associationInfoLabel);
      this.fileAssociationGroupBox.Location = new Point(6, 231);
      this.fileAssociationGroupBox.Name = "fileAssociationGroupBox";
      this.fileAssociationGroupBox.Size = new Size(542, 85);
      this.fileAssociationGroupBox.TabIndex = 4;
      this.fileAssociationGroupBox.TabStop = false;
      this.fileAssociationGroupBox.Text = "RCNET File Association";
      this.removeAssociationButton.FlatStyle = FlatStyle.System;
      this.removeAssociationButton.Location = new Point(146, 52);
      this.removeAssociationButton.Name = "removeAssociationButton";
      this.removeAssociationButton.Size = new Size(135, 23);
      this.removeAssociationButton.TabIndex = 2;
      this.removeAssociationButton.Text = "&Remove Association";
      this.removeAssociationButton.UseVisualStyleBackColor = true;
      this.removeAssociationButton.Click += new EventHandler(this.removeAssociationButton_Click);
      this.createAssociationButton.FlatStyle = FlatStyle.System;
      this.createAssociationButton.Location = new Point(9, 52);
      this.createAssociationButton.Name = "createAssociationButton";
      this.createAssociationButton.Size = new Size(131, 23);
      this.createAssociationButton.TabIndex = 1;
      this.createAssociationButton.Text = "Create &Association";
      this.createAssociationButton.UseVisualStyleBackColor = true;
      this.createAssociationButton.Click += new EventHandler(this.createAssociationButton_Click);
      this.associationInfoLabel.Location = new Point(6, 21);
      this.associationInfoLabel.Name = "associationInfoLabel";
      this.associationInfoLabel.Size = new Size(525, 28);
      this.associationInfoLabel.TabIndex = 0;
      this.associationInfoLabel.Text = "RCNET files can be associated with ReClass.NET. When you double-click a RCNET file, they will automatically be opened by ReClass.NET.";
      this.commentsGroupBox.Controls.Add((Control) this.showPluginInfoCheckBox);
      this.commentsGroupBox.Controls.Add((Control) this.showStringCheckBox);
      this.commentsGroupBox.Controls.Add((Control) this.showSymbolsCheckBox);
      this.commentsGroupBox.Controls.Add((Control) this.showRttiCheckBox);
      this.commentsGroupBox.Controls.Add((Control) this.showPointerCheckBox);
      this.commentsGroupBox.Controls.Add((Control) this.showIntegerCheckBox);
      this.commentsGroupBox.Controls.Add((Control) this.showFloatCheckBox);
      this.commentsGroupBox.Location = new Point(6, 39);
      this.commentsGroupBox.Name = "commentsGroupBox";
      this.commentsGroupBox.Size = new Size(265, 186);
      this.commentsGroupBox.TabIndex = 3;
      this.commentsGroupBox.TabStop = false;
      this.commentsGroupBox.Text = "Node Comments";
      this.showPluginInfoCheckBox.AutoSize = true;
      this.showPluginInfoCheckBox.Location = new Point(6, 157);
      this.showPluginInfoCheckBox.Name = "showPluginInfoCheckBox";
      this.showPluginInfoCheckBox.Size = new Size(111, 17);
      this.showPluginInfoCheckBox.TabIndex = 6;
      this.showPluginInfoCheckBox.Text = "Show Plugin Infos";
      this.showPluginInfoCheckBox.UseVisualStyleBackColor = true;
      this.showStringCheckBox.AutoSize = true;
      this.showStringCheckBox.Location = new Point(6, 134);
      this.showStringCheckBox.Name = "showStringCheckBox";
      this.showStringCheckBox.Size = new Size(88, 17);
      this.showStringCheckBox.TabIndex = 5;
      this.showStringCheckBox.Text = "Show Strings";
      this.showStringCheckBox.UseVisualStyleBackColor = true;
      this.showSymbolsCheckBox.AutoSize = true;
      this.showSymbolsCheckBox.Location = new Point(6, 111);
      this.showSymbolsCheckBox.Name = "showSymbolsCheckBox";
      this.showSymbolsCheckBox.Size = new Size(130, 17);
      this.showSymbolsCheckBox.TabIndex = 4;
      this.showSymbolsCheckBox.Text = "Show Debug Symbols";
      this.showSymbolsCheckBox.UseVisualStyleBackColor = true;
      this.showRttiCheckBox.AutoSize = true;
      this.showRttiCheckBox.Location = new Point(6, 88);
      this.showRttiCheckBox.Name = "showRttiCheckBox";
      this.showRttiCheckBox.Size = new Size(81, 17);
      this.showRttiCheckBox.TabIndex = 3;
      this.showRttiCheckBox.Text = "Show RTTI";
      this.showRttiCheckBox.UseVisualStyleBackColor = true;
      this.showPointerCheckBox.AutoSize = true;
      this.showPointerCheckBox.Location = new Point(6, 65);
      this.showPointerCheckBox.Name = "showPointerCheckBox";
      this.showPointerCheckBox.Size = new Size(94, 17);
      this.showPointerCheckBox.TabIndex = 2;
      this.showPointerCheckBox.Text = "Show Pointers";
      this.showPointerCheckBox.UseVisualStyleBackColor = true;
      this.showIntegerCheckBox.AutoSize = true;
      this.showIntegerCheckBox.Location = new Point(6, 42);
      this.showIntegerCheckBox.Name = "showIntegerCheckBox";
      this.showIntegerCheckBox.Size = new Size(124, 17);
      this.showIntegerCheckBox.TabIndex = 1;
      this.showIntegerCheckBox.Text = "Show Integer Values";
      this.showIntegerCheckBox.UseVisualStyleBackColor = true;
      this.showFloatCheckBox.AutoSize = true;
      this.showFloatCheckBox.Location = new Point(6, 19);
      this.showFloatCheckBox.Name = "showFloatCheckBox";
      this.showFloatCheckBox.Size = new Size(114, 17);
      this.showFloatCheckBox.TabIndex = 0;
      this.showFloatCheckBox.Text = "Show Float Values";
      this.showFloatCheckBox.UseVisualStyleBackColor = true;
      this.displayGroupBox.Controls.Add((Control) this.randomizeWindowTitleCheckBox);
      this.displayGroupBox.Controls.Add((Control) this.runAsAdminCheckBox);
      this.displayGroupBox.Controls.Add((Control) this.highlightChangedValuesCheckBox);
      this.displayGroupBox.Controls.Add((Control) this.showTextCheckBox);
      this.displayGroupBox.Controls.Add((Control) this.showNodeOffsetCheckBox);
      this.displayGroupBox.Controls.Add((Control) this.showNodeAddressCheckBox);
      this.displayGroupBox.Location = new Point(283, 39);
      this.displayGroupBox.Name = "displayGroupBox";
      this.displayGroupBox.Size = new Size(265, 160);
      this.displayGroupBox.TabIndex = 2;
      this.displayGroupBox.TabStop = false;
      this.displayGroupBox.Text = "Display";
      this.randomizeWindowTitleCheckBox.AutoSize = true;
      this.randomizeWindowTitleCheckBox.Location = new Point(6, 134);
      this.randomizeWindowTitleCheckBox.Name = "randomizeWindowTitleCheckBox";
      this.randomizeWindowTitleCheckBox.Size = new Size(137, 17);
      this.randomizeWindowTitleCheckBox.TabIndex = 5;
      this.randomizeWindowTitleCheckBox.Text = "Randomize window title";
      this.randomizeWindowTitleCheckBox.UseVisualStyleBackColor = true;
      this.runAsAdminCheckBox.AutoSize = true;
      this.runAsAdminCheckBox.Location = new Point(6, 111);
      this.runAsAdminCheckBox.Name = "runAsAdminCheckBox";
      this.runAsAdminCheckBox.Size = new Size(200, 17);
      this.runAsAdminCheckBox.TabIndex = 4;
      this.runAsAdminCheckBox.Text = "Run as administrator (requires restart)";
      this.runAsAdminCheckBox.UseVisualStyleBackColor = true;
      this.highlightChangedValuesCheckBox.AutoSize = true;
      this.highlightChangedValuesCheckBox.Location = new Point(6, 88);
      this.highlightChangedValuesCheckBox.Name = "highlightChangedValuesCheckBox";
      this.highlightChangedValuesCheckBox.Size = new Size(148, 17);
      this.highlightChangedValuesCheckBox.TabIndex = 3;
      this.highlightChangedValuesCheckBox.Text = "Highlight Changed Values";
      this.highlightChangedValuesCheckBox.UseVisualStyleBackColor = true;
      this.showTextCheckBox.AutoSize = true;
      this.showTextCheckBox.Location = new Point(6, 65);
      this.showTextCheckBox.Name = "showTextCheckBox";
      this.showTextCheckBox.Size = new Size(166, 17);
      this.showTextCheckBox.TabIndex = 2;
      this.showTextCheckBox.Text = "Show Textual Representation";
      this.showTextCheckBox.UseVisualStyleBackColor = true;
      this.showNodeOffsetCheckBox.AutoSize = true;
      this.showNodeOffsetCheckBox.Location = new Point(6, 42);
      this.showNodeOffsetCheckBox.Name = "showNodeOffsetCheckBox";
      this.showNodeOffsetCheckBox.Size = new Size(113, 17);
      this.showNodeOffsetCheckBox.TabIndex = 1;
      this.showNodeOffsetCheckBox.Text = "Show Node Offset";
      this.showNodeOffsetCheckBox.UseVisualStyleBackColor = true;
      this.showNodeAddressCheckBox.AutoSize = true;
      this.showNodeAddressCheckBox.Location = new Point(6, 19);
      this.showNodeAddressCheckBox.Name = "showNodeAddressCheckBox";
      this.showNodeAddressCheckBox.Size = new Size(123, 17);
      this.showNodeAddressCheckBox.TabIndex = 0;
      this.showNodeAddressCheckBox.Text = "Show Node Address";
      this.showNodeAddressCheckBox.UseVisualStyleBackColor = true;
      this.stayOnTopCheckBox.AutoSize = true;
      this.stayOnTopCheckBox.Location = new Point(6, 6);
      this.stayOnTopCheckBox.Name = "stayOnTopCheckBox";
      this.stayOnTopCheckBox.Size = new Size(187, 17);
      this.stayOnTopCheckBox.TabIndex = 1;
      this.stayOnTopCheckBox.Text = "Force ReClass.NET to stay on top";
      this.stayOnTopCheckBox.UseVisualStyleBackColor = true;
      this.colorsSettingTabPage.Controls.Add((Control) this.nodeColorGroupBox);
      this.colorsSettingTabPage.Controls.Add((Control) this.backgroundLabel);
      this.colorsSettingTabPage.Controls.Add((Control) this.backgroundColorBox);
      this.colorsSettingTabPage.Location = new Point(4, 22);
      this.colorsSettingTabPage.Name = "colorsSettingTabPage";
      this.colorsSettingTabPage.Padding = new Padding(3);
      this.colorsSettingTabPage.Size = new Size(554, 329);
      this.colorsSettingTabPage.TabIndex = 1;
      this.colorsSettingTabPage.Text = "Colors";
      this.colorsSettingTabPage.UseVisualStyleBackColor = true;
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeValueLabel);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodePluginLabel);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeHexValueColorBox);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodePluginColorBox);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeHexValueLabel);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeVTableLabel);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeOffsetColorBox);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeVTableColorBox);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeOffsetLabel);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeTextLabel);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeAddressColorBox);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeTextColorBox);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeAddressLabel);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeCommentLabel);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeHiddenColorBox);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeCommentColorBox);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeHiddenLabel);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeIndexLabel);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeSelectedColorBox);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeIndexColorBox);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeSelectedLabel);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeTypeColorBox);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeValueColorBox);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeTypeLabel);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeNameLabel);
      this.nodeColorGroupBox.Controls.Add((Control) this.nodeNameColorBox);
      this.nodeColorGroupBox.Location = new Point(9, 43);
      this.nodeColorGroupBox.Name = "nodeColorGroupBox";
      this.nodeColorGroupBox.Size = new Size(539, 225);
      this.nodeColorGroupBox.TabIndex = 28;
      this.nodeColorGroupBox.TabStop = false;
      this.nodeColorGroupBox.Text = "Node Colors";
      this.nodeValueLabel.AutoSize = true;
      this.nodeValueLabel.Location = new Point(9, 198);
      this.nodeValueLabel.Name = "nodeValueLabel";
      this.nodeValueLabel.Size = new Size(64, 13);
      this.nodeValueLabel.TabIndex = 17;
      this.nodeValueLabel.Text = "Value Color:";
      this.nodePluginLabel.AutoSize = true;
      this.nodePluginLabel.Location = new Point(286, 172);
      this.nodePluginLabel.Name = "nodePluginLabel";
      this.nodePluginLabel.Size = new Size(87, 13);
      this.nodePluginLabel.TabIndex = 27;
      this.nodePluginLabel.Text = "Plugin Info Color:";
      this.nodeHexValueColorBox.Color = Color.FromArgb(0, 0, 0);
      this.nodeHexValueColorBox.Location = new Point(133, 117);
      this.nodeHexValueColorBox.Name = "nodeHexValueColorBox";
      this.nodeHexValueColorBox.Size = new Size(123, 20);
      this.nodeHexValueColorBox.TabIndex = 2;
      this.nodePluginColorBox.Color = Color.FromArgb(0, 0, 0);
      this.nodePluginColorBox.Location = new Point(410, 169);
      this.nodePluginColorBox.Name = "nodePluginColorBox";
      this.nodePluginColorBox.Size = new Size(123, 20);
      this.nodePluginColorBox.TabIndex = 26;
      this.nodeHexValueLabel.AutoSize = true;
      this.nodeHexValueLabel.Location = new Point(9, 120);
      this.nodeHexValueLabel.Name = "nodeHexValueLabel";
      this.nodeHexValueLabel.Size = new Size(86, 13);
      this.nodeHexValueLabel.TabIndex = 3;
      this.nodeHexValueLabel.Text = "Hex Value Color:";
      this.nodeVTableLabel.AutoSize = true;
      this.nodeVTableLabel.Location = new Point(286, 94);
      this.nodeVTableLabel.Name = "nodeVTableLabel";
      this.nodeVTableLabel.Size = new Size(71, 13);
      this.nodeVTableLabel.TabIndex = 25;
      this.nodeVTableLabel.Text = "VTable Color:";
      this.nodeOffsetColorBox.Color = Color.FromArgb(0, 0, 0);
      this.nodeOffsetColorBox.Location = new Point(133, 91);
      this.nodeOffsetColorBox.Name = "nodeOffsetColorBox";
      this.nodeOffsetColorBox.Size = new Size(123, 20);
      this.nodeOffsetColorBox.TabIndex = 4;
      this.nodeVTableColorBox.Color = Color.FromArgb(0, 0, 0);
      this.nodeVTableColorBox.Location = new Point(410, 91);
      this.nodeVTableColorBox.Name = "nodeVTableColorBox";
      this.nodeVTableColorBox.Size = new Size(123, 20);
      this.nodeVTableColorBox.TabIndex = 24;
      this.nodeOffsetLabel.AutoSize = true;
      this.nodeOffsetLabel.Location = new Point(9, 94);
      this.nodeOffsetLabel.Name = "nodeOffsetLabel";
      this.nodeOffsetLabel.Size = new Size(65, 13);
      this.nodeOffsetLabel.TabIndex = 5;
      this.nodeOffsetLabel.Text = "Offset Color:";
      this.nodeTextLabel.AutoSize = true;
      this.nodeTextLabel.Location = new Point(286, 146);
      this.nodeTextLabel.Name = "nodeTextLabel";
      this.nodeTextLabel.Size = new Size(58, 13);
      this.nodeTextLabel.TabIndex = 23;
      this.nodeTextLabel.Text = "Text Color:";
      this.nodeAddressColorBox.Color = Color.FromArgb(0, 0, 0);
      this.nodeAddressColorBox.Location = new Point(133, 65);
      this.nodeAddressColorBox.Name = "nodeAddressColorBox";
      this.nodeAddressColorBox.Size = new Size(123, 20);
      this.nodeAddressColorBox.TabIndex = 6;
      this.nodeTextColorBox.Color = Color.FromArgb(0, 0, 0);
      this.nodeTextColorBox.Location = new Point(410, 143);
      this.nodeTextColorBox.Name = "nodeTextColorBox";
      this.nodeTextColorBox.Size = new Size(123, 20);
      this.nodeTextColorBox.TabIndex = 22;
      this.nodeAddressLabel.AutoSize = true;
      this.nodeAddressLabel.Location = new Point(9, 68);
      this.nodeAddressLabel.Name = "nodeAddressLabel";
      this.nodeAddressLabel.Size = new Size(75, 13);
      this.nodeAddressLabel.TabIndex = 7;
      this.nodeAddressLabel.Text = "Address Color:";
      this.nodeCommentLabel.AutoSize = true;
      this.nodeCommentLabel.Location = new Point(286, 120);
      this.nodeCommentLabel.Name = "nodeCommentLabel";
      this.nodeCommentLabel.Size = new Size(81, 13);
      this.nodeCommentLabel.TabIndex = 21;
      this.nodeCommentLabel.Text = "Comment Color:";
      this.nodeHiddenColorBox.Color = Color.FromArgb(0, 0, 0);
      this.nodeHiddenColorBox.Location = new Point(410, 18);
      this.nodeHiddenColorBox.Name = "nodeHiddenColorBox";
      this.nodeHiddenColorBox.Size = new Size(123, 20);
      this.nodeHiddenColorBox.TabIndex = 8;
      this.nodeCommentColorBox.Color = Color.FromArgb(0, 0, 0);
      this.nodeCommentColorBox.Location = new Point(410, 117);
      this.nodeCommentColorBox.Name = "nodeCommentColorBox";
      this.nodeCommentColorBox.Size = new Size(123, 20);
      this.nodeCommentColorBox.TabIndex = 20;
      this.nodeHiddenLabel.AutoSize = true;
      this.nodeHiddenLabel.Location = new Point(286, 21);
      this.nodeHiddenLabel.Name = "nodeHiddenLabel";
      this.nodeHiddenLabel.Size = new Size(71, 13);
      this.nodeHiddenLabel.TabIndex = 9;
      this.nodeHiddenLabel.Text = "Hidden Color:";
      this.nodeIndexLabel.AutoSize = true;
      this.nodeIndexLabel.Location = new Point(286, 68);
      this.nodeIndexLabel.Name = "nodeIndexLabel";
      this.nodeIndexLabel.Size = new Size(63, 13);
      this.nodeIndexLabel.TabIndex = 19;
      this.nodeIndexLabel.Text = "Index Color:";
      this.nodeSelectedColorBox.Color = Color.FromArgb(0, 0, 0);
      this.nodeSelectedColorBox.Location = new Point(133, 18);
      this.nodeSelectedColorBox.Name = "nodeSelectedColorBox";
      this.nodeSelectedColorBox.Size = new Size(123, 20);
      this.nodeSelectedColorBox.TabIndex = 10;
      this.nodeIndexColorBox.Color = Color.FromArgb(0, 0, 0);
      this.nodeIndexColorBox.Location = new Point(410, 65);
      this.nodeIndexColorBox.Name = "nodeIndexColorBox";
      this.nodeIndexColorBox.Size = new Size(123, 20);
      this.nodeIndexColorBox.TabIndex = 18;
      this.nodeSelectedLabel.AutoSize = true;
      this.nodeSelectedLabel.Location = new Point(9, 21);
      this.nodeSelectedLabel.Name = "nodeSelectedLabel";
      this.nodeSelectedLabel.Size = new Size(79, 13);
      this.nodeSelectedLabel.TabIndex = 11;
      this.nodeSelectedLabel.Text = "Selected Color:";
      this.nodeTypeColorBox.Color = Color.FromArgb(0, 0, 0);
      this.nodeTypeColorBox.Location = new Point(133, 143);
      this.nodeTypeColorBox.Name = "nodeTypeColorBox";
      this.nodeTypeColorBox.Size = new Size(123, 20);
      this.nodeTypeColorBox.TabIndex = 12;
      this.nodeValueColorBox.Color = Color.FromArgb(0, 0, 0);
      this.nodeValueColorBox.Location = new Point(133, 195);
      this.nodeValueColorBox.Name = "nodeValueColorBox";
      this.nodeValueColorBox.Size = new Size(123, 20);
      this.nodeValueColorBox.TabIndex = 16;
      this.nodeTypeLabel.AutoSize = true;
      this.nodeTypeLabel.Location = new Point(9, 146);
      this.nodeTypeLabel.Name = "nodeTypeLabel";
      this.nodeTypeLabel.Size = new Size(61, 13);
      this.nodeTypeLabel.TabIndex = 13;
      this.nodeTypeLabel.Text = "Type Color:";
      this.nodeNameLabel.AutoSize = true;
      this.nodeNameLabel.Location = new Point(9, 172);
      this.nodeNameLabel.Name = "nodeNameLabel";
      this.nodeNameLabel.Size = new Size(65, 13);
      this.nodeNameLabel.TabIndex = 15;
      this.nodeNameLabel.Text = "Name Color:";
      this.nodeNameColorBox.Color = Color.FromArgb(0, 0, 0);
      this.nodeNameColorBox.Location = new Point(133, 169);
      this.nodeNameColorBox.Name = "nodeNameColorBox";
      this.nodeNameColorBox.Size = new Size(123, 20);
      this.nodeNameColorBox.TabIndex = 14;
      this.backgroundLabel.AutoSize = true;
      this.backgroundLabel.Location = new Point(6, 14);
      this.backgroundLabel.Name = "backgroundLabel";
      this.backgroundLabel.Size = new Size(161, 13);
      this.backgroundLabel.TabIndex = 1;
      this.backgroundLabel.Text = "Memory View Background Color:";
      this.backgroundColorBox.Color = Color.FromArgb(0, 0, 0);
      this.backgroundColorBox.Location = new Point(175, 11);
      this.backgroundColorBox.Name = "backgroundColorBox";
      this.backgroundColorBox.Size = new Size(123, 20);
      this.backgroundColorBox.TabIndex = 0;
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.utf32TextSettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.utf32TextTypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.nuintSettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.nuintTypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.nintSettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.nintTypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.boolSettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.boolTypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.generatorInfoLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.functionPtrSettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.functionPtrTypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.utf16TextSettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.utf16TextTypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.utf8TextSettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.utf8TextTypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.matrix3x3SettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.matrix3x3TypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.matrix3x4SettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.matrix3x4TypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.matrix4x4SettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.matrix4x4TypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.vector2SettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.vector2TypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.vector3SettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.vector3TypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.vector4SettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.vector4TypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.doubleSettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.doubleTypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.floatSettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.floatTypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.uint64SettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.uint64TypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.uint32SettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.uint32TypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.uint16SettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.uint16TypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.uint8SettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.uint8TypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.int64SettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.int64TypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.int32SettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.int32TypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.int16SettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.int16TypeTextBox);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.int8SettingsLabel);
      this.typeDefinitionsSettingsTabPage.Controls.Add((Control) this.int8TypeTextBox);
      this.typeDefinitionsSettingsTabPage.Location = new Point(4, 22);
      this.typeDefinitionsSettingsTabPage.Name = "typeDefinitionsSettingsTabPage";
      this.typeDefinitionsSettingsTabPage.Padding = new Padding(3);
      this.typeDefinitionsSettingsTabPage.Size = new Size(554, 329);
      this.typeDefinitionsSettingsTabPage.TabIndex = 2;
      this.typeDefinitionsSettingsTabPage.Text = "Type Definitions";
      this.typeDefinitionsSettingsTabPage.UseVisualStyleBackColor = true;
      this.nuintSettingsLabel.AutoSize = true;
      this.nuintSettingsLabel.Location = new Point(6, 233);
      this.nuintSettingsLabel.Name = "nuintSettingsLabel";
      this.nuintSettingsLabel.Size = new Size(38, 13);
      this.nuintSettingsLabel.TabIndex = 50;
      this.nuintSettingsLabel.Text = "NUInt:";
      this.nuintTypeTextBox.Location = new Point(98, 230);
      this.nuintTypeTextBox.Name = "nuintTypeTextBox";
      this.nuintTypeTextBox.Size = new Size(120, 20);
      this.nuintTypeTextBox.TabIndex = 49;
      this.nintSettingsLabel.AutoSize = true;
      this.nintSettingsLabel.Location = new Point(6, 123);
      this.nintSettingsLabel.Name = "nintSettingsLabel";
      this.nintSettingsLabel.Size = new Size(30, 13);
      this.nintSettingsLabel.TabIndex = 48;
      this.nintSettingsLabel.Text = "NInt:";
      this.nintTypeTextBox.Location = new Point(98, 120);
      this.nintTypeTextBox.Name = "nintTypeTextBox";
      this.nintTypeTextBox.Size = new Size(120, 20);
      this.nintTypeTextBox.TabIndex = 47;
      this.boolSettingsLabel.AutoSize = true;
      this.boolSettingsLabel.Location = new Point(254, 35);
      this.boolSettingsLabel.Name = "boolSettingsLabel";
      this.boolSettingsLabel.Size = new Size(31, 13);
      this.boolSettingsLabel.TabIndex = 46;
      this.boolSettingsLabel.Text = "Bool:";
      this.boolTypeTextBox.Location = new Point(346, 32);
      this.boolTypeTextBox.Name = "boolTypeTextBox";
      this.boolTypeTextBox.Size = new Size(120, 20);
      this.boolTypeTextBox.TabIndex = 45;
      this.generatorInfoLabel.AutoSize = true;
      this.generatorInfoLabel.Location = new Point(6, 6);
      this.generatorInfoLabel.Name = "generatorInfoLabel";
      this.generatorInfoLabel.Size = new Size(236, 13);
      this.generatorInfoLabel.TabIndex = 44;
      this.generatorInfoLabel.Text = "These types are used to generate the C++ code:";
      this.functionPtrSettingsLabel.AutoSize = true;
      this.functionPtrSettingsLabel.Location = new Point(254, (int) byte.MaxValue);
      this.functionPtrSettingsLabel.Name = "functionPtrSettingsLabel";
      this.functionPtrSettingsLabel.Size = new Size(87, 13);
      this.functionPtrSettingsLabel.TabIndex = 43;
      this.functionPtrSettingsLabel.Text = "Function Pointer:";
      this.functionPtrTypeTextBox.Location = new Point(346, 252);
      this.functionPtrTypeTextBox.Name = "functionPtrTypeTextBox";
      this.functionPtrTypeTextBox.Size = new Size(120, 20);
      this.functionPtrTypeTextBox.TabIndex = 42;
      this.utf16TextSettingsLabel.AutoSize = true;
      this.utf16TextSettingsLabel.Location = new Point(254, 211);
      this.utf16TextSettingsLabel.Name = "utf16TextSettingsLabel";
      this.utf16TextSettingsLabel.Size = new Size(43, 13);
      this.utf16TextSettingsLabel.TabIndex = 39;
      this.utf16TextSettingsLabel.Text = "UTF16:";
      this.utf16TextTypeTextBox.Location = new Point(346, 208);
      this.utf16TextTypeTextBox.Name = "utf16TextTypeTextBox";
      this.utf16TextTypeTextBox.Size = new Size(120, 20);
      this.utf16TextTypeTextBox.TabIndex = 38;
      this.utf8TextSettingsLabel.AutoSize = true;
      this.utf8TextSettingsLabel.Location = new Point(254, 189);
      this.utf8TextSettingsLabel.Name = "utf8TextSettingsLabel";
      this.utf8TextSettingsLabel.Size = new Size(37, 13);
      this.utf8TextSettingsLabel.TabIndex = 35;
      this.utf8TextSettingsLabel.Text = "UTF8:";
      this.utf8TextTypeTextBox.Location = new Point(346, 186);
      this.utf8TextTypeTextBox.Name = "utf8TextTypeTextBox";
      this.utf8TextTypeTextBox.Size = new Size(120, 20);
      this.utf8TextTypeTextBox.TabIndex = 34;
      this.matrix3x3SettingsLabel.AutoSize = true;
      this.matrix3x3SettingsLabel.Location = new Point(254, 123);
      this.matrix3x3SettingsLabel.Name = "matrix3x3SettingsLabel";
      this.matrix3x3SettingsLabel.Size = new Size(64, 13);
      this.matrix3x3SettingsLabel.TabIndex = 33;
      this.matrix3x3SettingsLabel.Text = "Matrix (3x3):";
      this.matrix3x3TypeTextBox.Location = new Point(346, 120);
      this.matrix3x3TypeTextBox.Name = "matrix3x3TypeTextBox";
      this.matrix3x3TypeTextBox.Size = new Size(120, 20);
      this.matrix3x3TypeTextBox.TabIndex = 32;
      this.matrix3x4SettingsLabel.AutoSize = true;
      this.matrix3x4SettingsLabel.Location = new Point(254, 145);
      this.matrix3x4SettingsLabel.Name = "matrix3x4SettingsLabel";
      this.matrix3x4SettingsLabel.Size = new Size(64, 13);
      this.matrix3x4SettingsLabel.TabIndex = 31;
      this.matrix3x4SettingsLabel.Text = "Matrix (3x4):";
      this.matrix3x4TypeTextBox.Location = new Point(346, 142);
      this.matrix3x4TypeTextBox.Name = "matrix3x4TypeTextBox";
      this.matrix3x4TypeTextBox.Size = new Size(120, 20);
      this.matrix3x4TypeTextBox.TabIndex = 30;
      this.matrix4x4SettingsLabel.AutoSize = true;
      this.matrix4x4SettingsLabel.Location = new Point(254, 167);
      this.matrix4x4SettingsLabel.Name = "matrix4x4SettingsLabel";
      this.matrix4x4SettingsLabel.Size = new Size(64, 13);
      this.matrix4x4SettingsLabel.TabIndex = 29;
      this.matrix4x4SettingsLabel.Text = "Matrix (4x4):";
      this.matrix4x4TypeTextBox.Location = new Point(346, 164);
      this.matrix4x4TypeTextBox.Name = "matrix4x4TypeTextBox";
      this.matrix4x4TypeTextBox.Size = new Size(120, 20);
      this.matrix4x4TypeTextBox.TabIndex = 28;
      this.vector2SettingsLabel.AutoSize = true;
      this.vector2SettingsLabel.Location = new Point(254, 57);
      this.vector2SettingsLabel.Name = "vector2SettingsLabel";
      this.vector2SettingsLabel.Size = new Size(47, 13);
      this.vector2SettingsLabel.TabIndex = 27;
      this.vector2SettingsLabel.Text = "Vector2:";
      this.vector2TypeTextBox.Location = new Point(346, 54);
      this.vector2TypeTextBox.Name = "vector2TypeTextBox";
      this.vector2TypeTextBox.Size = new Size(120, 20);
      this.vector2TypeTextBox.TabIndex = 26;
      this.vector3SettingsLabel.AutoSize = true;
      this.vector3SettingsLabel.Location = new Point(254, 79);
      this.vector3SettingsLabel.Name = "vector3SettingsLabel";
      this.vector3SettingsLabel.Size = new Size(47, 13);
      this.vector3SettingsLabel.TabIndex = 25;
      this.vector3SettingsLabel.Text = "Vector3:";
      this.vector3TypeTextBox.Location = new Point(346, 76);
      this.vector3TypeTextBox.Name = "vector3TypeTextBox";
      this.vector3TypeTextBox.Size = new Size(120, 20);
      this.vector3TypeTextBox.TabIndex = 24;
      this.vector4SettingsLabel.AutoSize = true;
      this.vector4SettingsLabel.Location = new Point(254, 101);
      this.vector4SettingsLabel.Name = "vector4SettingsLabel";
      this.vector4SettingsLabel.Size = new Size(47, 13);
      this.vector4SettingsLabel.TabIndex = 23;
      this.vector4SettingsLabel.Text = "Vector4:";
      this.vector4TypeTextBox.Location = new Point(346, 98);
      this.vector4TypeTextBox.Name = "vector4TypeTextBox";
      this.vector4TypeTextBox.Size = new Size(120, 20);
      this.vector4TypeTextBox.TabIndex = 22;
      this.doubleSettingsLabel.AutoSize = true;
      this.doubleSettingsLabel.Location = new Point(6, 277);
      this.doubleSettingsLabel.Name = "doubleSettingsLabel";
      this.doubleSettingsLabel.Size = new Size(44, 13);
      this.doubleSettingsLabel.TabIndex = 21;
      this.doubleSettingsLabel.Text = "Double:";
      this.doubleTypeTextBox.Location = new Point(98, 274);
      this.doubleTypeTextBox.Name = "doubleTypeTextBox";
      this.doubleTypeTextBox.Size = new Size(120, 20);
      this.doubleTypeTextBox.TabIndex = 20;
      this.floatSettingsLabel.AutoSize = true;
      this.floatSettingsLabel.Location = new Point(6, (int) byte.MaxValue);
      this.floatSettingsLabel.Name = "floatSettingsLabel";
      this.floatSettingsLabel.Size = new Size(33, 13);
      this.floatSettingsLabel.TabIndex = 19;
      this.floatSettingsLabel.Text = "Float:";
      this.floatTypeTextBox.Location = new Point(98, 252);
      this.floatTypeTextBox.Name = "floatTypeTextBox";
      this.floatTypeTextBox.Size = new Size(120, 20);
      this.floatTypeTextBox.TabIndex = 18;
      this.uint64SettingsLabel.AutoSize = true;
      this.uint64SettingsLabel.Location = new Point(6, 211);
      this.uint64SettingsLabel.Name = "uint64SettingsLabel";
      this.uint64SettingsLabel.Size = new Size(42, 13);
      this.uint64SettingsLabel.TabIndex = 17;
      this.uint64SettingsLabel.Text = "UInt64:";
      this.uint64TypeTextBox.Location = new Point(98, 208);
      this.uint64TypeTextBox.Name = "uint64TypeTextBox";
      this.uint64TypeTextBox.Size = new Size(120, 20);
      this.uint64TypeTextBox.TabIndex = 16;
      this.uint32SettingsLabel.AutoSize = true;
      this.uint32SettingsLabel.Location = new Point(6, 189);
      this.uint32SettingsLabel.Name = "uint32SettingsLabel";
      this.uint32SettingsLabel.Size = new Size(42, 13);
      this.uint32SettingsLabel.TabIndex = 15;
      this.uint32SettingsLabel.Text = "UInt32:";
      this.uint32TypeTextBox.Location = new Point(98, 186);
      this.uint32TypeTextBox.Name = "uint32TypeTextBox";
      this.uint32TypeTextBox.Size = new Size(120, 20);
      this.uint32TypeTextBox.TabIndex = 14;
      this.uint16SettingsLabel.AutoSize = true;
      this.uint16SettingsLabel.Location = new Point(6, 167);
      this.uint16SettingsLabel.Name = "uint16SettingsLabel";
      this.uint16SettingsLabel.Size = new Size(42, 13);
      this.uint16SettingsLabel.TabIndex = 13;
      this.uint16SettingsLabel.Text = "UInt16:";
      this.uint16TypeTextBox.Location = new Point(98, 164);
      this.uint16TypeTextBox.Name = "uint16TypeTextBox";
      this.uint16TypeTextBox.Size = new Size(120, 20);
      this.uint16TypeTextBox.TabIndex = 12;
      this.uint8SettingsLabel.AutoSize = true;
      this.uint8SettingsLabel.Location = new Point(6, 145);
      this.uint8SettingsLabel.Name = "uint8SettingsLabel";
      this.uint8SettingsLabel.Size = new Size(36, 13);
      this.uint8SettingsLabel.TabIndex = 11;
      this.uint8SettingsLabel.Text = "UInt8:";
      this.uint8TypeTextBox.Location = new Point(98, 142);
      this.uint8TypeTextBox.Name = "uint8TypeTextBox";
      this.uint8TypeTextBox.Size = new Size(120, 20);
      this.uint8TypeTextBox.TabIndex = 10;
      this.int64SettingsLabel.AutoSize = true;
      this.int64SettingsLabel.Location = new Point(6, 101);
      this.int64SettingsLabel.Name = "int64SettingsLabel";
      this.int64SettingsLabel.Size = new Size(34, 13);
      this.int64SettingsLabel.TabIndex = 9;
      this.int64SettingsLabel.Text = "Int64:";
      this.int64TypeTextBox.Location = new Point(98, 98);
      this.int64TypeTextBox.Name = "int64TypeTextBox";
      this.int64TypeTextBox.Size = new Size(120, 20);
      this.int64TypeTextBox.TabIndex = 8;
      this.int32SettingsLabel.AutoSize = true;
      this.int32SettingsLabel.Location = new Point(6, 79);
      this.int32SettingsLabel.Name = "int32SettingsLabel";
      this.int32SettingsLabel.Size = new Size(34, 13);
      this.int32SettingsLabel.TabIndex = 7;
      this.int32SettingsLabel.Text = "Int32:";
      this.int32TypeTextBox.Location = new Point(98, 76);
      this.int32TypeTextBox.Name = "int32TypeTextBox";
      this.int32TypeTextBox.Size = new Size(120, 20);
      this.int32TypeTextBox.TabIndex = 6;
      this.int16SettingsLabel.AutoSize = true;
      this.int16SettingsLabel.Location = new Point(6, 57);
      this.int16SettingsLabel.Name = "int16SettingsLabel";
      this.int16SettingsLabel.Size = new Size(34, 13);
      this.int16SettingsLabel.TabIndex = 5;
      this.int16SettingsLabel.Text = "Int16:";
      this.int16TypeTextBox.Location = new Point(98, 54);
      this.int16TypeTextBox.Name = "int16TypeTextBox";
      this.int16TypeTextBox.Size = new Size(120, 20);
      this.int16TypeTextBox.TabIndex = 4;
      this.int8SettingsLabel.AutoSize = true;
      this.int8SettingsLabel.Location = new Point(6, 35);
      this.int8SettingsLabel.Name = "int8SettingsLabel";
      this.int8SettingsLabel.Size = new Size(28, 13);
      this.int8SettingsLabel.TabIndex = 3;
      this.int8SettingsLabel.Text = "Int8:";
      this.int8TypeTextBox.Location = new Point(98, 32);
      this.int8TypeTextBox.Name = "int8TypeTextBox";
      this.int8TypeTextBox.Size = new Size(120, 20);
      this.int8TypeTextBox.TabIndex = 2;
      this.bannerBox.Dock = DockStyle.Top;
      this.bannerBox.Icon = (Image) Resources.B32x32_Cogs;
      this.bannerBox.Location = new Point(0, 0);
      this.bannerBox.Name = "bannerBox";
      this.bannerBox.Size = new Size(586, 48);
      this.bannerBox.TabIndex = 2;
      this.bannerBox.Text = "Configure the global settings.";
      this.bannerBox.Title = "Settings";
      this.utf32TextSettingsLabel.AutoSize = true;
      this.utf32TextSettingsLabel.Location = new Point(254, 233);
      this.utf32TextSettingsLabel.Name = "utf32TextSettingsLabel";
      this.utf32TextSettingsLabel.Size = new Size(43, 13);
      this.utf32TextSettingsLabel.TabIndex = 52;
      this.utf32TextSettingsLabel.Text = "UTF32:";
      this.utf32TextTypeTextBox.Location = new Point(346, 230);
      this.utf32TextTypeTextBox.Name = "utf32TextTypeTextBox";
      this.utf32TextTypeTextBox.Size = new Size(120, 20);
      this.utf32TextTypeTextBox.TabIndex = 51;
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(586, 427);
      this.Controls.Add((Control) this.bannerBox);
      this.Controls.Add((Control) this.settingsTabControl);
      this.FormBorderStyle = FormBorderStyle.FixedDialog;
      this.MaximizeBox = false;
      this.MinimizeBox = false;
      this.Name = nameof (SettingsForm);
      this.ShowInTaskbar = false;
      this.StartPosition = FormStartPosition.CenterParent;
      this.Text = "ReClass.NET - Settings";
      this.settingsTabControl.ResumeLayout(false);
      this.generalSettingsTabPage.ResumeLayout(false);
      this.generalSettingsTabPage.PerformLayout();
      this.fileAssociationGroupBox.ResumeLayout(false);
      this.commentsGroupBox.ResumeLayout(false);
      this.commentsGroupBox.PerformLayout();
      this.displayGroupBox.ResumeLayout(false);
      this.displayGroupBox.PerformLayout();
      this.colorsSettingTabPage.ResumeLayout(false);
      this.colorsSettingTabPage.PerformLayout();
      this.nodeColorGroupBox.ResumeLayout(false);
      this.nodeColorGroupBox.PerformLayout();
      this.typeDefinitionsSettingsTabPage.ResumeLayout(false);
      this.typeDefinitionsSettingsTabPage.PerformLayout();
      this.bannerBox.EndInit();
      this.ResumeLayout(false);
    }
  }
}
